package models

// seedData is the static canonical model registry. Each entry provides:
//   - A stable canonical ID (provider-independent, kebab-case)
//   - Provider-specific model IDs for all known providers
//   - AiderAliases matching names seen in the Aider polyglot YAML/leaderboard
//   - An initial "seed_blended" score (0-100) based on published benchmarks
//     and released Aider polyglot results — updated by the live fetcher
//   - Seed input/output costs per million tokens (USD) — overwritten by live
//     OpenRouter pricing fetcher on each refresh cycle
//
// Tier mapping:
//
//	flagship  ≥ 70  → master/critic tier
//	mid       50-69 → sonnet sub-agent tier
//	fast      30-49 → haiku sub-agent tier
//	tiny      < 30  → local/free fallback
var seedData = []CanonicalModel{
	// ── Anthropic ────────────────────────────────────────────────────────────
	{
		ID: "claude-opus-4", Name: "Claude Opus 4", Family: "claude", Tier: "flagship",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-opus-4-20250514",
			"openrouter": "anthropic/claude-opus-4",
		},
		AiderAliases:    []string{"claude-opus-4-20250514", "claude-opus-4"},
		Scores:          map[string]float64{"seed_blended": 72.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  15.0,
		OutputCostPer1M: 75.0,
		Notes:           "original Opus 4; heavy reasoning + best tool-use compliance",
		ContextWindow:   200000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "claude-opus-4-7", Name: "Claude Opus 4.7", Family: "claude", Tier: "flagship",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-opus-4-7",
			"openrouter": "anthropic/claude-opus-4.7",
		},
		AiderAliases:    []string{"claude-opus-4.7", "claude opus 4.7"},
		Scores:          map[string]float64{"seed_blended": 71.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  5.0,
		OutputCostPer1M: 25.0,
		Notes:           "Opus 4.7; cheaper and faster than Opus 4; strong all-round",
		ContextWindow:   200000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "claude-sonnet-4", Name: "Claude Sonnet 4", Family: "claude", Tier: "flagship",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-sonnet-4-6",
			"openrouter": "anthropic/claude-sonnet-4.6",
		},
		AiderAliases:    []string{"claude-sonnet-4-20250514", "claude-sonnet-4"},
		Scores:          map[string]float64{"seed_blended": 57.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  3.0,
		OutputCostPer1M: 15.0,
		Notes:           "strong default; high tool-use compliance",
		ContextWindow:   200000,
		MaxOutputTokens: 64000,
	},
	{
		ID: "claude-3-7-sonnet", Name: "Claude 3.7 Sonnet", Family: "claude", Tier: "flagship",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-3-7-sonnet-20250219",
			"openrouter": "anthropic/claude-3-7-sonnet",
		},
		AiderAliases:    []string{"claude-3-7-sonnet-20250219", "claude-3-7-sonnet"},
		Scores:          map[string]float64{"seed_blended": 63.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  3.0,
		OutputCostPer1M: 15.0,
		Notes:           "extended thinking model; strong on complex reasoning",
		ContextWindow:   200000,
		MaxOutputTokens: 64000,
		ThinkingCostPer1M: 3.0,
	},
	{
		ID: "claude-3-5-sonnet", Name: "Claude 3.5 Sonnet", Family: "claude", Tier: "mid",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-3-5-sonnet-20241022",
			"openrouter": "anthropic/claude-3-5-sonnet",
		},
		AiderAliases:    []string{"claude-3-5-sonnet-20241022", "claude-3-5-sonnet"},
		Scores:          map[string]float64{"seed_blended": 52.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  3.0,
		OutputCostPer1M: 15.0,
		Notes:           "previous-generation Sonnet; solid tool-use",
		ContextWindow:   200000,
		MaxOutputTokens: 8096,
	},
	{
		ID: "claude-haiku-4", Name: "Claude Haiku 4.5", Family: "claude", Tier: "fast",
		ProviderIDs: map[string]string{
			"anthropic":  "claude-haiku-4-5-20251001",
			"openrouter": "anthropic/claude-haiku-4.5",
		},
		AiderAliases:    []string{"claude-haiku-4-5", "claude-haiku-4"},
		Scores:          map[string]float64{"seed_blended": 42.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  1.0,
		OutputCostPer1M: 5.0,
		Notes:           "cheap + fast; excellent for sub-agent legwork",
		ContextWindow:   200000,
		MaxOutputTokens: 8096,
	},

	// ── OpenAI ───────────────────────────────────────────────────────────────
	{
		ID: "gpt-5.4-pro", Name: "GPT-5.4 Pro", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5.4-pro",
			"openrouter": "openai/gpt-5.4-pro",
		},
		AiderAliases:    []string{"gpt-5.4-pro"},
		Scores:          map[string]float64{"seed_blended": 91.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  30.0,
		OutputCostPer1M: 180.0,
		Notes:           "GPT-5.4 premium; high-effort reasoning",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "gpt-5.4", Name: "GPT-5.4", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5.4",
			"openrouter": "openai/gpt-5.4",
		},
		AiderAliases:    []string{"gpt-5.4"},
		Scores:          map[string]float64{"seed_blended": 90.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  2.5,
		OutputCostPer1M: 15.0,
		Notes:           "GPT-5.4 standard; strong coding + reasoning",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "gpt-5.4-mini", Name: "GPT-5.4 Mini", Family: "gpt", Tier: "mid",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5.4-mini",
			"openrouter": "openai/gpt-5.4-mini",
		},
		AiderAliases:    []string{"gpt-5.4-mini"},
		Scores:          map[string]float64{"seed_blended": 72.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.75,
		OutputCostPer1M: 4.5,
		Notes:           "GPT-5.4 Mini; efficient sub-agent tier",
		ContextWindow:   128000,
		MaxOutputTokens: 16384,
	},
	{
		ID: "gpt-5-pro", Name: "GPT-5 Pro", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5-pro",
			"openrouter": "openai/gpt-5-pro",
		},
		AiderAliases:    []string{"gpt-5-pro"},
		Scores:          map[string]float64{"seed_blended": 89.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  15.0,
		OutputCostPer1M: 120.0,
		Notes:           "GPT-5 Pro; premium reasoning budget",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "gpt-5", Name: "GPT-5", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5",
			"openrouter": "openai/gpt-5",
		},
		AiderAliases:    []string{"gpt-5"},
		Scores:          map[string]float64{"seed_blended": 88.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  1.25,
		OutputCostPer1M: 10.0,
		Notes:           "OpenAI flagship; top Aider polyglot score",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "gpt-5-mini", Name: "GPT-5 Mini", Family: "gpt", Tier: "fast",
		ProviderIDs: map[string]string{
			"openai":     "gpt-5-mini",
			"openrouter": "openai/gpt-5-mini",
		},
		AiderAliases:    []string{"gpt-5-mini"},
		Scores:          map[string]float64{"seed_blended": 55.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.25,
		OutputCostPer1M: 2.0,
		Notes:           "GPT-5 Mini; cheap + capable sub-agent",
		ContextWindow:   128000,
		MaxOutputTokens: 16384,
	},
	{
		ID: "o3-pro", Name: "o3-pro", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "o3-pro",
			"openrouter": "openai/o3-pro",
		},
		AiderAliases:    []string{"o3-pro"},
		Scores:          map[string]float64{"seed_blended": 84.9},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  20.0,
		OutputCostPer1M: 80.0,
		Notes:           "deep reasoning at highest effort; expensive",
		ContextWindow:   200000,
		MaxOutputTokens: 100000,
	},
	{
		ID: "o3", Name: "o3", Family: "gpt", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openai":     "o3",
			"openrouter": "openai/o3",
		},
		AiderAliases:    []string{"o3"},
		Scores:          map[string]float64{"seed_blended": 81.3},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  2.0,
		OutputCostPer1M: 8.0,
		Notes:           "strong reasoning; high effort mode recommended",
		ContextWindow:   200000,
		MaxOutputTokens: 100000,
	},
	{
		ID: "o4-mini", Name: "o4-mini", Family: "gpt", Tier: "mid",
		ProviderIDs: map[string]string{
			"openai":     "o4-mini",
			"openrouter": "openai/o4-mini",
		},
		AiderAliases:    []string{"o4-mini"},
		Scores:          map[string]float64{"seed_blended": 72.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  1.1,
		OutputCostPer1M: 4.4,
		Notes:           "reasoning at sub-agent budget",
		ContextWindow:   200000,
		MaxOutputTokens: 100000,
	},
	{
		ID: "o3-mini", Name: "o3-mini", Family: "gpt", Tier: "mid",
		ProviderIDs: map[string]string{
			"openai":     "o3-mini",
			"openrouter": "openai/o3-mini",
		},
		AiderAliases:    []string{"o3-mini"},
		Scores:          map[string]float64{"seed_blended": 60.4},
		Capabilities:    []string{"reasoning"},
		InputCostPer1M:  1.1,
		OutputCostPer1M: 4.4,
		Notes:           "reasoning at sub-agent budget",
		ContextWindow:   200000,
		MaxOutputTokens: 65536,
	},
	{
		ID: "gpt-4o", Name: "GPT-4o", Family: "gpt", Tier: "mid",
		ProviderIDs: map[string]string{
			"openai":     "gpt-4o",
			"openrouter": "openai/gpt-4o",
		},
		AiderAliases:    []string{"gpt-4o", "gpt-4o-2024-11-20", "gpt-4o-2024-08-06"},
		Scores:          map[string]float64{"seed_blended": 42.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  2.5,
		OutputCostPer1M: 10.0,
		Notes:           "all-rounder; solid tool use",
		ContextWindow:   128000,
		MaxOutputTokens: 16384,
	},
	{
		ID: "gpt-4o-mini", Name: "GPT-4o mini", Family: "gpt", Tier: "fast",
		ProviderIDs: map[string]string{
			"openai":     "gpt-4o-mini",
			"openrouter": "openai/gpt-4o-mini",
		},
		AiderAliases:    []string{"gpt-4o-mini", "gpt-4o-mini-2024-07-18"},
		Scores:          map[string]float64{"seed_blended": 25.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.15,
		OutputCostPer1M: 0.6,
		Notes:           "cheap sub-agent default",
		ContextWindow:   128000,
		MaxOutputTokens: 16384,
	},

	// ── Google Gemini ─────────────────────────────────────────────────────────
	{
		ID: "gemini-2-5-pro", Name: "Gemini 2.5 Pro", Family: "gemini", Tier: "flagship",
		ProviderIDs: map[string]string{
			"gemini":     "gemini-2.5-pro",
			"openrouter": "google/gemini-2.5-pro-preview",
		},
		AiderAliases: []string{
			"gemini 2.5 pro preview 06-05", "gemini 2.5 pro preview 05-06",
			"gemini 2.5 pro preview 03-25", "gemini-2.5-pro-preview",
			"gemini-2.5-pro",
		},
		Scores:          map[string]float64{"seed_blended": 80.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  1.25,
		OutputCostPer1M: 10.0,
		Notes:           "long context; competitive coding; generous free quota",
		ContextWindow:   1000000,
		MaxOutputTokens: 65536,
		ThinkingCostPer1M: 3.5,
	},
	{
		ID: "gemini-2-5-flash", Name: "Gemini 2.5 Flash", Family: "gemini", Tier: "mid",
		ProviderIDs: map[string]string{
			"gemini":     "gemini-2.5-flash",
			"openrouter": "google/gemini-2.5-flash-preview",
		},
		AiderAliases: []string{
			"gemini-2.5-flash-preview", "gemini 2.5 flash preview",
			"gemini-2.5-flash-preview-05-20", "gemini-2.5-flash",
		},
		Scores:          map[string]float64{"seed_blended": 55.1},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  0.3,
		OutputCostPer1M: 2.5,
		Notes:           "fast, free quota; thinking mode available",
		ContextWindow:   1000000,
		MaxOutputTokens: 65536,
		ThinkingCostPer1M: 3.5,
	},
	{
		ID: "gemini-2-0-flash", Name: "Gemini 2.0 Flash", Family: "gemini", Tier: "fast",
		ProviderIDs: map[string]string{
			"openrouter": "google/gemini-2.0-flash-001",
		},
		AiderAliases:    []string{"gemini-2.0-flash", "gemini 2.0 flash"},
		Scores:          map[string]float64{"seed_blended": 38.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.1,
		OutputCostPer1M: 0.4,
		Notes:           "gemini-2.0-flash SHUT DOWN June 2026; use gemini-2.5-flash or gemini-3-flash-preview",
		ContextWindow:   1000000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "gemini-3-flash", Name: "Gemini 3 Flash Preview", Family: "gemini", Tier: "mid",
		ProviderIDs: map[string]string{
			"gemini":     "gemini-3-flash-preview",
			"openrouter": "google/gemini-3-flash-preview",
		},
		AiderAliases:    []string{"gemini-3-flash-preview", "gemini 3 flash"},
		Scores:          map[string]float64{"seed_blended": 60.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  0.3,
		OutputCostPer1M: 2.5,
		Notes:           "Gemini 3 Flash Preview; recommended replacement for 2.5 Flash",
		ContextWindow:   1000000,
		MaxOutputTokens: 65536,
	},
	{
		ID: "gemini-3-1-pro", Name: "Gemini 3.1 Pro Preview", Family: "gemini", Tier: "flagship",
		ProviderIDs: map[string]string{
			"gemini":     "gemini-3.1-pro-preview",
			"openrouter": "google/gemini-3.1-pro-preview",
		},
		AiderAliases:    []string{"gemini-3.1-pro-preview", "gemini 3.1 pro"},
		Scores:          map[string]float64{"seed_blended": 83.0},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  1.25,
		OutputCostPer1M: 10.0,
		Notes:           "Gemini 3.1 Pro Preview; recommended replacement for 2.5 Pro",
		ContextWindow:   1000000,
		MaxOutputTokens: 65536,
	},
	{
		ID: "gemini-2-5-flash-lite", Name: "Gemini 2.5 Flash-Lite", Family: "gemini", Tier: "fast",
		ProviderIDs: map[string]string{
			"gemini":     "gemini-2.5-flash-lite",
			"openrouter": "google/gemini-2.5-flash-lite-preview",
		},
		AiderAliases:    []string{"gemini-2.5-flash-lite", "gemini 2.5 flash lite"},
		Scores:          map[string]float64{"seed_blended": 42.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.1,
		OutputCostPer1M: 0.4,
		Notes:           "Gemini 2.5 Flash-Lite; most cost-efficient Gemini; stable",
		ContextWindow:   1000000,
		MaxOutputTokens: 65536,
	},

	// ── DeepSeek ─────────────────────────────────────────────────────────────
	{
		ID: "deepseek-v3", Name: "DeepSeek V3", Family: "deepseek", Tier: "flagship",
		ProviderIDs: map[string]string{
			"deepseek":    "deepseek-chat",
			"together":    "deepseek-ai/DeepSeek-V3",
			"huggingface": "deepseek-ai/DeepSeek-V3",
			"openrouter":  "deepseek/deepseek-chat",
		},
		AiderAliases: []string{
			"deepseek-chat", "deepseek v3", "deepseek v3 (0324)",
			"deepseek-v3.2-exp (chat)", "deepseek-v3.2-exp",
		},
		Scores:          map[string]float64{"seed_blended": 62.0},
		InputCostPer1M:  0.15,
		OutputCostPer1M: 0.75,
		Notes:           "DeepSeek V3 Chat; very cheap; strong code",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "deepseek-r1", Name: "DeepSeek R1", Family: "deepseek", Tier: "flagship",
		ProviderIDs: map[string]string{
			"deepseek":    "deepseek-reasoner",
			"together":    "deepseek-ai/DeepSeek-R1",
			"huggingface": "deepseek-ai/DeepSeek-R1",
			"openrouter":  "deepseek/deepseek-r1",
		},
		AiderAliases: []string{
			"deepseek-reasoner", "deepseek r1", "deepseek r1 (0528)",
			"deepseek-v3.2-exp (reasoner)",
		},
		Scores:          map[string]float64{"seed_blended": 72.0},
		Capabilities:    []string{"reasoning"},
		InputCostPer1M:  0.7,
		OutputCostPer1M: 2.5,
		Notes:           "DeepSeek R1; reasoning + code-strong; very cheap",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
		ThinkingCostPer1M: 2.19,
	},
	{
		ID: "deepseek-v4-flash", Name: "DeepSeek V4 Flash", Family: "deepseek", Tier: "mid",
		ProviderIDs: map[string]string{
			"deepseek": "deepseek-v4-flash",
		},
		AiderAliases:    []string{"deepseek-v4-flash"},
		Scores:          map[string]float64{"seed_blended": 60.0},
		Capabilities:    []string{"reasoning"},
		InputCostPer1M:  0.15,
		OutputCostPer1M: 0.6,
		Notes:           "fast, supports thinking mode; replaces deepseek-chat",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "deepseek-v4-pro", Name: "DeepSeek V4 Pro", Family: "deepseek", Tier: "flagship",
		ProviderIDs: map[string]string{
			"deepseek": "deepseek-v4-pro",
			"together": "deepseek-ai/DeepSeek-V4-Pro",
		},
		AiderAliases:    []string{"deepseek-v4-pro"},
		Scores:          map[string]float64{"seed_blended": 74.0},
		Capabilities:    []string{"reasoning"},
		InputCostPer1M:  0.5,
		OutputCostPer1M: 2.0,
		Notes:           "premium reasoning; 75% off until May 2026",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},

	// ── Meta Llama ────────────────────────────────────────────────────────────
	{
		ID: "llama-4-maverick", Name: "Llama 4 Maverick", Family: "llama", Tier: "mid",
		ProviderIDs: map[string]string{
			"openrouter": "meta-llama/llama-4-maverick",
		},
		AiderAliases:    []string{"llama-4-maverick", "llama 4 maverick"},
		Scores:          map[string]float64{"seed_blended": 52.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.15,
		OutputCostPer1M: 0.6,
		Notes:           "Meta Llama 4 Maverick; strong multimodal mid-tier",
		ContextWindow:   1000000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "llama-4-scout", Name: "Llama 4 Scout", Family: "llama", Tier: "fast",
		ProviderIDs: map[string]string{
			"groq":       "meta-llama/llama-4-scout-17b-16e-instruct",
			"openrouter": "meta-llama/llama-4-scout",
		},
		AiderAliases:    []string{"llama-4-scout", "llama 4 scout"},
		Scores:          map[string]float64{"seed_blended": 40.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.08,
		OutputCostPer1M: 0.3,
		Notes:           "Meta Llama 4 Scout; fast + cheap with long context",
		ContextWindow:   10000000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "llama-3-3-70b", Name: "Llama 3.3 70B", Family: "llama", Tier: "mid",
		ProviderIDs: map[string]string{
			"groq":         "llama-3.3-70b-versatile",
			"huggingface":  "meta-llama/Llama-3.3-70B-Instruct",
			"together":     "meta-llama/Llama-3.3-70B-Instruct-Turbo",
			"openrouter":   "meta-llama/llama-3.3-70b-instruct",
			"ollama":       "llama3.3",
			"ollama-cloud": "llama3.3:70b",
		},
		AiderAliases: []string{
			"llama-3.3-70b", "llama 3.3 70b",
			"meta-llama/llama-3.3-70b-instruct",
		},
		Scores:          map[string]float64{"seed_blended": 42.0},
		InputCostPer1M:  0.08,
		OutputCostPer1M: 0.3,
		Notes:           "fast open-source all-rounder; low TTFT on Groq/Cerebras",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "llama-3-1-8b", Name: "Llama 3.1 8B", Family: "llama", Tier: "tiny",
		ProviderIDs: map[string]string{
			"groq":     "llama-3.1-8b-instant",
			"cerebras": "llama3.1-8b",
		},
		AiderAliases:    []string{"llama-3.1-8b-instant", "llama3.1-8b"},
		Scores:          map[string]float64{"seed_blended": 18.0},
		InputCostPer1M:  0.05,
		OutputCostPer1M: 0.08,
		Notes:           "tiny + fast; trivial tasks only",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},

	// ── Qwen ─────────────────────────────────────────────────────────────────
	{
		ID: "qwen3-235b", Name: "Qwen3 235B A22B", Family: "qwen", Tier: "flagship",
		ProviderIDs: map[string]string{
			"together":   "Qwen/Qwen3-235B-A22B-Instruct-2507-tput",
			"openrouter": "qwen/qwen3-235b-a22b",
		},
		AiderAliases:    []string{"qwen3 235b a22b", "qwen3-235b-a22b"},
		Scores:          map[string]float64{"seed_blended": 59.6},
		InputCostPer1M:  0.46,
		OutputCostPer1M: 1.82,
		Notes:           "Qwen3 MoE flagship; strong coding",
		ContextWindow:   262000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "qwen3-5-397b", Name: "Qwen3.5 397B A17B", Family: "qwen", Tier: "flagship",
		ProviderIDs: map[string]string{
			"together":   "Qwen/Qwen3.5-397B-A17B",
			"openrouter": "qwen/qwen3.5-397b-a17b",
		},
		AiderAliases:    []string{"qwen3.5-397b-a17b", "qwen3.5 397b"},
		Scores:          map[string]float64{"seed_blended": 68.0},
		InputCostPer1M:  0.6,
		OutputCostPer1M: 3.6,
		Notes:           "Qwen3.5 MoE flagship; 262K context",
		ContextWindow:   262000,
		MaxOutputTokens: 64000,
	},
	{
		ID: "qwen3-coder", Name: "Qwen3 Coder 480B", Family: "qwen", Tier: "mid",
		ProviderIDs: map[string]string{
			"together":   "Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8",
			"openrouter": "qwen/qwen3-coder",
			"opencode":   "qwen3-coder-480b",
		},
		AiderAliases:    []string{"qwen3-coder", "qwen3 coder"},
		Scores:          map[string]float64{"seed_blended": 55.0},
		InputCostPer1M:  0.3,
		OutputCostPer1M: 0.6,
		Notes:           "code-specialized Qwen3",
		ContextWindow:   128000,
		MaxOutputTokens: 16384,
	},
	{
		ID: "qwen-2-5-coder-32b", Name: "Qwen 2.5 Coder 32B", Family: "qwen", Tier: "mid",
		ProviderIDs: map[string]string{
			"huggingface":  "Qwen/Qwen2.5-Coder-32B-Instruct",
			"together":     "Qwen/Qwen2.5-Coder-32B-Instruct",
			"openrouter":   "qwen/qwen-2.5-coder-32b-instruct",
			"ollama":       "qwen2.5-coder:32b",
			"ollama-cloud": "qwen2.5-coder:32b",
		},
		AiderAliases:    []string{"qwen2.5-coder-32b-instruct", "qwen/qwen2.5-coder-32b-instruct"},
		Scores:          map[string]float64{"seed_blended": 45.0},
		InputCostPer1M:  0.07,
		OutputCostPer1M: 0.15,
		Notes:           "code-specialized; punches above its weight",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},

	// ── Mistral ───────────────────────────────────────────────────────────────
	{
		ID: "mistral-large", Name: "Mistral Large", Family: "mistral", Tier: "mid",
		ProviderIDs: map[string]string{
			"mistral":    "mistral-large-latest",
			"openrouter": "mistralai/mistral-large",
		},
		AiderAliases:    []string{"mistral-large-latest", "mistral-large"},
		Scores:          map[string]float64{"seed_blended": 48.0},
		InputCostPer1M:  2.0,
		OutputCostPer1M: 6.0,
		Notes:           "Mistral flagship; solid general purpose",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "codestral", Name: "Codestral", Family: "mistral", Tier: "mid",
		ProviderIDs: map[string]string{
			"mistral":    "codestral-latest",
			"openrouter": "mistralai/codestral-2501",
		},
		AiderAliases:    []string{"codestral-latest", "codestral"},
		Scores:          map[string]float64{"seed_blended": 44.0},
		InputCostPer1M:  0.3,
		OutputCostPer1M: 0.9,
		Notes:           "code-specialized Mistral model",
		ContextWindow:   256000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "mixtral-8x7b", Name: "Mixtral 8x7B", Family: "mistral", Tier: "fast",
		ProviderIDs: map[string]string{
			"openrouter":  "mistralai/mixtral-8x7b-instruct",
			"huggingface": "mistralai/Mixtral-8x7B-Instruct-v0.1",
		},
		AiderAliases:    []string{"mixtral-8x7b-instruct-v0.1", "mixtral 8x7b"},
		Scores:          map[string]float64{"seed_blended": 32.0},
		InputCostPer1M:  0.24,
		OutputCostPer1M: 0.24,
		Notes:           "Mixtral MoE 8x7B; ageing but cost-effective",
		ContextWindow:   32000,
		MaxOutputTokens: 4096,
	},
	{
		ID: "magistral-medium", Name: "Magistral Medium", Family: "mistral", Tier: "flagship",
		ProviderIDs: map[string]string{
			"mistral":    "magistral-medium-latest",
			"openrouter": "mistralai/magistral-medium-2507",
		},
		AiderAliases:    []string{"magistral-medium-2507", "magistral-medium"},
		Scores:          map[string]float64{"seed_blended": 70.0},
		Capabilities:    []string{"reasoning"},
		InputCostPer1M:  2.0,
		OutputCostPer1M: 5.0,
		Notes:           "Mistral reasoning flagship; free tier available",
		ContextWindow:   40000,
		MaxOutputTokens: 16384,
		ThinkingCostPer1M: 5.0,
	},
	{
		ID: "devstral-small", Name: "Devstral Small", Family: "mistral", Tier: "mid",
		ProviderIDs: map[string]string{
			"mistral":    "devstral-small-2507",
			"openrouter": "mistralai/devstral-small-2507",
		},
		AiderAliases:    []string{"devstral-small-2507", "devstral-small"},
		Scores:          map[string]float64{"seed_blended": 58.0},
		InputCostPer1M:  0.1,
		OutputCostPer1M: 0.3,
		Notes:           "Mistral agentic coding model; free tier",
		ContextWindow:   32000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "mistral-small", Name: "Mistral Small 3.2", Family: "mistral", Tier: "fast",
		ProviderIDs: map[string]string{
			"mistral":    "mistral-small-latest",
			"openrouter": "mistralai/mistral-small-2506",
		},
		AiderAliases:    []string{"mistral-small-2506", "mistral-small"},
		Scores:          map[string]float64{"seed_blended": 38.0},
		InputCostPer1M:  0.1,
		OutputCostPer1M: 0.3,
		Notes:           "Mistral Small 3.2; efficient general purpose, free tier",
		ContextWindow:   32000,
		MaxOutputTokens: 8192,
	},

	// ── xAI Grok ─────────────────────────────────────────────────────────────
	{
		ID: "grok-4", Name: "Grok 4", Family: "grok", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openrouter": "x-ai/grok-4",
		},
		AiderAliases:    []string{"grok-4", "grok 4"},
		Scores:          map[string]float64{"seed_blended": 79.6},
		Capabilities:    []string{"vision", "reasoning"},
		InputCostPer1M:  3.0,
		OutputCostPer1M: 15.0,
		Notes:           "xAI flagship; strong reasoning",
		ContextWindow:   256000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "grok-3", Name: "Grok 3", Family: "grok", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openrouter": "x-ai/grok-3-beta",
		},
		AiderAliases:    []string{"grok-3-beta", "grok 3 beta", "grok-3"},
		Scores:          map[string]float64{"seed_blended": 53.3},
		InputCostPer1M:  3.0,
		OutputCostPer1M: 15.0,
		Notes:           "xAI Grok 3; strong general purpose",
		ContextWindow:   131000,
		MaxOutputTokens: 8192,
	},

	// ── Kimi / MoonshotAI ────────────────────────────────────────────────────
	{
		ID: "kimi-k2.6", Name: "Kimi K2.6", Family: "kimi", Tier: "flagship",
		ProviderIDs: map[string]string{
			"together":   "moonshotai/Kimi-K2.6",
			"openrouter": "moonshotai/kimi-k2.6",
		},
		AiderAliases:    []string{"kimi k2.6", "kimi-k2.6"},
		Scores:          map[string]float64{"seed_blended": 61.0},
		InputCostPer1M:  0.75,
		OutputCostPer1M: 3.5,
		Notes:           "Moonshot K2.6; latest Kimi flagship",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "kimi-k2", Name: "Kimi K2", Family: "kimi", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openrouter": "moonshotai/kimi-k2",
			"opencode":   "kimi-k2",
		},
		AiderAliases:    []string{"kimi k2", "kimi-k2"},
		Scores:          map[string]float64{"seed_blended": 59.1},
		InputCostPer1M:  0.57,
		OutputCostPer1M: 2.3,
		Notes:           "Moonshot K2; strong coding",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "kimi-k2.5", Name: "Kimi K2.5", Family: "kimi", Tier: "flagship",
		ProviderIDs: map[string]string{
			"together":   "moonshotai/Kimi-K2.5",
			"openrouter": "moonshotai/kimi-k2.5",
		},
		AiderAliases:    []string{"kimi k2.5", "kimi-k2.5"},
		Scores:          map[string]float64{"seed_blended": 58.5},
		InputCostPer1M:  0.5,
		OutputCostPer1M: 2.8,
		Notes:           "Moonshot K2.5; strong coding + tool use",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},

	// ── MiniMax ───────────────────────────────────────────────────────────────
	{
		ID: "minimax-m2.7", Name: "MiniMax M2.7", Family: "minimax", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openrouter": "minimax/minimax-m2.7",
		},
		AiderAliases:    []string{"minimax m2.7", "minimax-m2.7"},
		Scores:          map[string]float64{"seed_blended": 58.0},
		InputCostPer1M:  0.3,
		OutputCostPer1M: 1.2,
		Notes:           "MiniMax M2.7; latest MiniMax flagship",
		ContextWindow:   1000000,
		MaxOutputTokens: 32768,
	},

	// ── NVIDIA Nemotron ───────────────────────────────────────────────────────
	{
		ID: "nemotron-3-super-120b", Name: "Nemotron 3 Super 120B", Family: "nemotron", Tier: "flagship",
		ProviderIDs: map[string]string{
			"openrouter": "nvidia/nemotron-3-super-120b-a12b",
		},
		AiderAliases:    []string{"nemotron-3-super-120b-a12b", "nemotron 3 super"},
		Scores:          map[string]float64{"seed_blended": 62.0},
		InputCostPer1M:  0.09,
		OutputCostPer1M: 0.45,
		Notes:           "NVIDIA 120B hybrid MoE (12B active); strong agentic workloads",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "llama-3.3-nemotron-super-49b", Name: "Llama 3.3 Nemotron Super 49B", Family: "nemotron", Tier: "mid",
		ProviderIDs: map[string]string{
			"openrouter": "nvidia/llama-3.3-nemotron-super-49b-v1.5",
		},
		AiderAliases:    []string{"llama-3.3-nemotron-super-49b-v1.5", "llama 3.3 nemotron super 49b"},
		Scores:          map[string]float64{"seed_blended": 52.0},
		InputCostPer1M:  0.1,
		OutputCostPer1M: 0.4,
		Notes:           "NVIDIA fine-tune of Llama 3.3 70B; agentic + RAG",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "nemotron-3-nano-30b", Name: "Nemotron 3 Nano 30B", Family: "nemotron", Tier: "fast",
		ProviderIDs: map[string]string{
			"openrouter": "nvidia/nemotron-3-nano-30b-a3b",
		},
		AiderAliases:    []string{"nemotron-3-nano-30b-a3b", "nemotron 3 nano 30b"},
		Scores:          map[string]float64{"seed_blended": 37.0},
		InputCostPer1M:  0.05,
		OutputCostPer1M: 0.2,
		Notes:           "NVIDIA 30B MoE (3B active); efficient edge/agent model",
		ContextWindow:   128000,
		MaxOutputTokens: 4096,
	},
	{
		ID: "nemotron-nano-9b", Name: "Nemotron Nano 9B", Family: "nemotron", Tier: "tiny",
		ProviderIDs: map[string]string{
			"openrouter": "nvidia/nemotron-nano-9b-v2",
		},
		AiderAliases:    []string{"nemotron-nano-9b-v2", "nemotron nano 9b"},
		Scores:          map[string]float64{"seed_blended": 26.0},
		InputCostPer1M:  0.04,
		OutputCostPer1M: 0.16,
		Notes:           "NVIDIA 9B unified reasoning/chat; smallest Nemotron",
		ContextWindow:   128000,
		MaxOutputTokens: 4096,
	},

	// ── GPT-OSS ───────────────────────────────────────────────────────────────
	{
		ID: "gpt-oss-120b", Name: "GPT-OSS 120B", Family: "gpt", Tier: "mid",
		ProviderIDs: map[string]string{
			"groq":       "openai/gpt-oss-120b",
			"cerebras":   "gpt-oss-120b",
			"together":   "openai/gpt-oss-120b",
			"openrouter": "openai/gpt-oss-120b",
			"opencode":   "gpt-oss-120b",
		},
		AiderAliases:    []string{"gpt-oss-120b", "openai/gpt-oss-120b"},
		Scores:          map[string]float64{"seed_blended": 48.0},
		InputCostPer1M:  0.04,
		OutputCostPer1M: 0.18,
		Notes:           "OpenAI OSS 120B; strong free-tier option",
		ContextWindow:   128000,
		MaxOutputTokens: 32768,
	},
	{
		ID: "gpt-oss-20b", Name: "GPT-OSS 20B", Family: "gpt", Tier: "fast",
		ProviderIDs: map[string]string{
			"groq":       "openai/gpt-oss-20b",
			"cerebras":   "gpt-oss-20b",
			"together":   "openai/gpt-oss-20b",
			"openrouter": "openai/gpt-oss-20b",
		},
		AiderAliases:    []string{"gpt-oss-20b", "openai/gpt-oss-20b"},
		Scores:          map[string]float64{"seed_blended": 35.0},
		InputCostPer1M:  0.04,
		OutputCostPer1M: 0.14,
		Notes:           "OpenAI OSS 20B; fastest (~1000 t/s on Groq/Cerebras)",
		ContextWindow:   32000,
		MaxOutputTokens: 8192,
	},

	// ── GLM ───────────────────────────────────────────────────────────────────
	{
		ID: "glm-4-5-air", Name: "GLM 4.5 Air", Family: "glm", Tier: "mid",
		ProviderIDs: map[string]string{
			"openrouter": "z-ai/glm-4.5-air",
		},
		AiderAliases:    []string{"glm-4.5-air"},
		Scores:          map[string]float64{"seed_blended": 40.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  0.13,
		OutputCostPer1M: 0.85,
		Notes:           "Zhipu GLM 4.5 Air; free on OpenRouter",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
	{
		ID: "glm-4-7", Name: "Z.ai GLM 4.7", Family: "glm", Tier: "flagship",
		ProviderIDs: map[string]string{
			"cerebras":   "zai-glm-4.7",
			"together":   "zai-org/GLM-5.1",
			"openrouter": "z-ai/glm-4.7",
		},
		AiderAliases:    []string{"zai-glm-4.7", "glm-4.7", "GLM-5.1"},
		Scores:          map[string]float64{"seed_blended": 65.0},
		Capabilities:    []string{"vision"},
		InputCostPer1M:  1.4,
		OutputCostPer1M: 4.4,
		Notes:           "Z.ai GLM 4.7 (355B); strong coding + tool use; on Cerebras at preview",
		ContextWindow:   128000,
		MaxOutputTokens: 8192,
	},
}
