package config

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

// LoadEnvFile reads simple KEY=VALUE pairs from a file, ignoring blanks and
// comments. Returns an empty map if the file doesn't exist.
func LoadEnvFile(path string) map[string]string {
	out := map[string]string{}
	b, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return out
	}
	for _, line := range strings.Split(string(b), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		i := strings.Index(line, "=")
		if i <= 0 {
			continue
		}
		k := strings.TrimSpace(line[:i])
		v := strings.TrimSpace(line[i+1:])
		v = strings.Trim(v, `"'`)
		out[k] = v
	}
	return out
}

// MergeEnv overlays new values on top of base. Empty values delete keys.
func MergeEnv(base, overlay map[string]string) map[string]string {
	out := map[string]string{}
	for k, v := range base {
		out[k] = v
	}
	for k, v := range overlay {
		if v == "" {
			delete(out, k)
		} else {
			out[k] = v
		}
	}
	return out
}

// SetOrClear writes value if it differs from the implicit default; otherwise
// removes the key so the file stays tidy.
func SetOrClear(m map[string]string, key, value, defaultValue string) {
	if value == "" || value == defaultValue {
		delete(m, key)
		return
	}
	m[key] = value
}

// WriteEnvFile writes the map to path with 0600 perms (file may contain
// secrets). Keys are sorted for stable diffs.
func WriteEnvFile(path string, kv map[string]string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	keys := make([]string, 0, len(kv))
	for k := range kv {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	var sb strings.Builder
	sb.WriteString("# Generated by ageni. Edit by hand or use `ageni init` / the in-TUI settings page.\n")
	for _, k := range keys {
		v := kv[k]
		if needsQuote(v) {
			v = strconv.Quote(v)
		}
		sb.WriteString(fmt.Sprintf("%s=%s\n", k, v))
	}
	return os.WriteFile(path, []byte(sb.String()), 0o600)
}

func needsQuote(v string) bool {
	return strings.ContainsAny(v, " \t\"'#=")
}
